name: nexgai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - pip=25.1
  - ca-certificates=2025.2.25
  - openssl=3.0.16
  - setuptools=78.1.1
  - wheel=0.45.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiohttp-retry==2.9.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2025.7.9
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cohere==5.16.1
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - datasets==4.0.0
      - dill==0.3.8
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - fastapi==0.116.0
      - fastavro==1.11.1
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - greenlet==3.2.3
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.33.2
      - idna==3.10
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.26
      - langchain-community==0.3.27
      - langchain-huggingface==0.3.0
      - langchain-openai==0.3.27
      - langspan==0.3.68
      - langgraph==0.5.2
      - langgraph-sdk==0.1.72
      - sentence-transformers==5.0.0
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - openai==1.94.0
      - orjson==3.10.18
      - pydantic==2.11.7
      - pygments==2.19.2
      - pypdf==5.7.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - tqdm==4.67.1
      - transformers==4.53.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.23.0
